### ISSUE TITLE
Ethstats

### ISSUE THREAD

**Issue by keorn** [paritytech/parity-deploy#30]
`./parity-deploy.sh --config aura --ethstats`, go to 3001 and no nodes appear

**Comment by ddorgan** [comment]
Again, 100% sure you have an up to date repo? This was an issue a few days ago. I see a host when I checkout parity-deploy and run this command.

There does seem to be some new issue not showing the transaction numbers since after 1.6.10, I'll look into that.

Let me know if you can reproduce this one.

**Comment by ddorgan** [comment]
Any update on this Peter?
