### ISSUE TITLE
No UI

### ISSUE THREAD

**Issue by keorn** [paritytech/parity-deploy#31]
`./parity-deploy.sh --config aura` (or ` --release nightly`), nothing on 8180

**Comment by daverod24** [comment]
the same happens to me

I made some changes to open the UI inside the containers:

install ntpdate

``` sudo ntpdate -s us.pool.ntp.org ```
then in the authority.toml enter the ui
```
[ui]
force = true
disable = false
port = 8180
interface = "0.0.0.0"
```
and later

``` /parity/parity --chain /parity/spec.json --config /parity/authority.toml -d /parity/data/ signer new-token ```

and sometimes he takes it but now he has not caught me again

**Comment by ddorgan** [comment]
You did have an up to date repo right? So you can reproduce using:
``` git clone git@github.com:paritytech/parity-deploy.git ; cd parity-deploy ; ./parity-deploy.sh --config aura ```
Then run curl:  ``` curl -s http://localhost:8180 | grep parity ``` you don't get output:
  <link rel="shortcut icon" href="parity-logo-black-no-text.png"><link href="styles/index.4d982b90d6.css" rel="stylesheet"></head> ???

I can't seem to.

**Comment by ddorgan** [comment]
Any update on this Peter?

**Comment by melnikaite** [comment]
I have no UI as well running `git clone git@github.com:paritytech/parity-deploy.git; cd parity-deploy; ./parity-deploy.sh --config dev; docker-compose up` and `curl -s http://localhost:8180` returns nothing.

The problem is that docker-compose.yml doesn't contain a list of exposed ports. Even after exposing `8180` it suggest me to run `parity signer new-token` because token from output logs doesn't work.
